<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>circus.robocalc</groupId>
  <artifactId>circus.robocalc.robochart.epsilon.isacircus.parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>../circus.robocalc.robochart.epsilon.isacircus</module>
    <module>../circus.robocalc.robochart.epsilon.isacircus.feature</module>
    <module>../circus.robocalc.robochart.epsilon.isacircus.site</module>
  </modules>

<build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-maven-plugin</artifactId>
        <version>4.0.6</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.eclipse.m2e</groupId>
          <artifactId>lifecycle-mapping</artifactId>
          <version>1.0.0</version>
          <configuration>
            <lifecycleMappingMetadata>
              <pluginExecutions>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>org.eclipse.tycho</groupId>
                    <artifactId>tycho-packaging-plugin</artifactId>
                    <versionRange>[0,)</versionRange>
                    <goals>
                      <goal>build-qualifier</goal>
                      <goal>validate-id</goal>
                      <goal>validate-version</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore/>
                  </action>
                </pluginExecution>
              </pluginExecutions>
            </lifecycleMappingMetadata>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <repositories>
    <repository>
      <id>epsilon</id>
      <layout>p2</layout>
      <url>https://download.eclipse.org/epsilon/updates/2.4/</url>
    </repository>
    <repository>
      <id>eclipse-2022-12</id>
      <layout>p2</layout>
      <url>https://download.eclipse.org/releases/2022-12/</url>
    </repository>
    <repository>
      <id>local-eclipse</id>
      <layout>p2</layout>
      <url>file:///C:/Users/fy668/local-p2/</url>
    </repository>
  </repositories>

</project>